repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.4
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: update-requirements
        name: update-requirements
        entry: bash -c 'pipenv requirements > requirements.txt && git add requirements.txt'
        language: system
        types: [python]
