namespace-packages = ["src/ui/components/"]
exclude = [
  ".git",
  "assets",
  "docs",
  "i18n",
  ".idea",
  ".mypy_cache",
  ".tox",
  ".venv",
]
preview = true
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
  "ANN401",  # any-type
  "B006",    # mutable-argument-default
  "CPY001",  # missing-copyright-notice
  "D100",    # undocumented-public-module
  "D107",    # undocumented-public-init
  "D203",    # one-blank-line-before-class
  "D212",    # multi-line-summary-first-line
  "D401",    # non-imperative-mood
  "DOC201", # docstring-missing-returns
  "DOC402", # docstring-missing-yields
  "DOC501", # docstring-missing-exception
  "E402",    # module-level-import-not-at-top-level
  "FBT001",  # boolean-type-hint-positional-argument
  "FBT002",  # boolean-type-hint-positional-argument
  "FBT003",  # boolean-positional-value-in-call
  "PD901",   # pandas-df-variable-name
  "PLC0415", # import-outside-top-level
  "PTH120",  # os-path-dirname
]
fixable = ["ALL"]
unfixable = []
extend-select = [
  "B033",    # duplicate-value
  "C416",    # unnecessary-comprehension
  "D211",    # no-blank-line-before-class
  "D213",    # multi-line-summary-second-line
  "D419",    # empty-docstring
  "E501",    # line-too-long
  "E722",    # bare-except
  "F401",    # unused-import
  "F704",    # yield-outside-function
  "F706",    # return-outside-function
  "F841",    # unused-variable
  "PLC0414", # useless-import-alias
  "PLC2401", # non-ascii-name
  "PLC2801", # unnecessary-dunder-call
  "PLC3002", # unnecessary-direct-lambda-call
  "PLE0101", # return-in-init
  "PLE0115", # nonlocal-and-global
  "PLE0116", # continue-in-finally
  "PLE0117", # nonlocal-without-binding
  "PLE0241", # duplicate-bases
  "PLE0302", # unexpected-special-method-signature
  "PLE0604", # invalid-all-object
  "PLE0605", # invalid-all-format
  "PLE0643", # potential-index-error
  "PLE0704", # misplaced-bare-raise
  "PLE1141", # dict-iter-missing-items
  "PLE1142", # await-outside-async
  "PLE1205", # logging-too-many-args
  "PLE1206", # logging-too-few-args
  "PLE1307", # bad-string-format-type
  "PLE1310", # bad-str-strip-call
  "PLE1507", # invalid-envvar-value
  "PLE1519", # singledispatch-method
  "PLE1520", # singledispatchmethod-function
  "PLE2502", # bidirectional-unicode
  "PLE2510", # invalid-character-backspace
  "PLE2512", # invalid-character-sub
  "PLE2513", # invalid-character-esc
  "PLE2514", # invalid-character-nul
  "PLE2515", # invalid-character-zero-width-space
  "PLE4703", # modified-iterating-set
  "PLR0124", # comparison-with-itself
  "PLR0202", # no-classmethod-decorator
  "PLR0203", # no-staticmethod-decorator
  "PLR0206", # property-with-parameters
  "PLR0904", # too-many-public-methods
  "PLR0911", # too-many-return-statements
  "PLR0912", # too-many-branches
  "PLR0913", # too-many-arguments
  "PLR0914", # too-many-locals
  "PLR0915", # too-many-statements
  "PLR0916", # too-many-boolean-expressions
  "PLR0917", # too-many-positional
  "PLR1702", # too-many-nested-blocks
  "PLR1704", # redefined-argument-from-local
  "PLR1711", # useless-return
  "PLR1733", # unnecessary-dict-index-lookup
  "PLR1736", # unnecessary-list-index-lookup
  "PLW0108", # unnecessary-lambda
  "PLW0120", # useless-else-on-loop
  "PLW0127", # self-assigning-variable
  "PLW0128", # redeclared-assigned-name
  "PLW0129", # assert-on-string-literal
  "PLW0131", # named-expr-without-context
  "PLW0177", # nan-comparison
  "PLW0211", # bad-staticmethod-argument
  "PLW0245", # super-without-brackets
  "PLW0406", # import-self
  "PLW0602", # global-variable-not-assigned
  "PLW0603", # global-statement
  "PLW0604", # global-at-module-level
  "PLW0711", # binary-op-exception
  "PLW1501", # bad-open-mode
  "PLW1508", # invalid-envvar-default
  "PLW1509", # subprocess-popen-preexec-fn
  "PLW1514", # unspecified-encoding
  "PLW2101", # useless-with-lock
  "PLW3301", # nested-min-max
  "UP004",   # useless-object-inheritance
  "W291",    # trailing-whitespace
]
